name: Check documentation
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    name: "check doc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DocEvaluator
        uses: compf/DocEvaluator@action
        with:
          include: |-
            [
              "*.java"
            ]
          exclude: "[]"
          metrics: |-
            [
              {
                "weight": 1,
                "metric_name": "simple_comment",
                "params": {
                  "getter_pattern": "(get.*)|(is.*)",
                  "setter_pattern": "set.*",
                  "ignore_getter_setter": false
                },
                "unique_name": "simple_comment_0"
              }
            ]
          absolute_threshold: 50
          builder: default_builder
          parser: java
          path_weights: "[]"
          component_weights: "[]"
          default_path_weight: 1
          default_component_weight: 1
          state_manager: file
          relative_threshold: 30
      - name: Add & commit
        if: always()
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: .evaluator_last_state.txt
